### ISSUE TITLE
main.ts doesn't export PathFinding correctly

### ISSUE THREAD

**Issue by mathiasbn** [projectstorm/react-diagrams#336]
In main.ts you
`export * from "./routing/PathFinding";`
But `PathFinding` uses default, which means it isn't exportet.
As I understand it, you should either remove `default` from Pathfinding.ts
or write:
`export {default} from './module.js';`
is `main.ts`

**Comment by eouin** [comment]
That issue is blocking us trying to extend the LinkWidget. Can you fix it?

**Comment by lopesc** [comment]
@dylanvorster +1, same issue

**Comment by dylanvorster** [comment]
should be fixed in the new Lerna system

**Comment by vadimshvetsov** [comment]
Right now it's still not reachable. Maybe we could consider merging #806 for removing `PathFinding` copies from projects?
