### ISSUE TITLE
Click on a link (DefaultLinkWidget) ignores `setLocked` read-only mode of the model and allows to add a point to the link.

### ISSUE THREAD

**Issue by sompylasar** [projectstorm/react-diagrams#73]
https://github.com/projectstorm/react-diagrams/blob/f36a8cf30444757d53ecb01e2c4c5cc05b02d70a/src/defaults/DefaultLinkWidget.ts#L164-L170

Related: https://github.com/projectstorm/react-diagrams/issues/71

**Comment by dylanvorster** [comment]
Fixed in 2.5.2

**Comment by chlumper** [comment]
@dylanvorster Thanks for providing a fix for this problem!

However I think you missed to add the adaption for links with complex line:
https://github.com/projectstorm/react-diagrams/blob/6d653aa0b67b43e618f768296e716f2f78f959b5/src/defaults/DefaultLinkWidget.tsx#L177-L183
in comparsion to (at simple line)
https://github.com/projectstorm/react-diagrams/blob/6d653aa0b67b43e618f768296e716f2f78f959b5/src/defaults/DefaultLinkWidget.tsx#L131-L137

I created a pull request #81 with a fix for it.
Would be great if you could release a npm package with the fix. Thanks!
